server:
  port: 8001

# spring config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

# springdoc
springdoc:
  api-docs:
    path: /cloud/api-docs
  swagger-ui:
    path: /cloud/swagger-ui.html

# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.atxiong.cloud.entity.payment
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# zipkin 配置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。
  endpoints:
    web:
      exposure:  # 暴露 服务的各项信息
        include: "*"
      base-path: '/actuator'
