server:
  port: 2002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.ip}:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${db.username}
    password: ${db.password}
  cloud:
    openfeign:
      client:
        config:
          cloud-payment-service:
            read-timeout: 20000
      httpclient: # 配置httpClient
        hc5:
          enabled: true
      compression: #开启请求压缩格式为GZIP
        request:
          enabled: true
          min-request-size: 2048
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true

#seata 配置
seata:
  registry:
    type: nacos
    nacos:
      server-addr: ${nacos.address}
      namespace: ""
      group: SEATA_GROUP
      application: seata-server
      username: ${nacos.username}
      password: ${nacos.password}
  tx-service-group: default_tx_group # 默认事务组，由它获取TC服务器集群名称
  service:
    vgroup-mapping:  #点击源码分析
      default_tx_group: default # 事务组与TC服务集群映射关系
  data-source-proxy-mode: AT

# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.atxiong.cloud.entity.payment
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# zipkin 配置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。

logging:
  level:
    io:
      seata: info # seata 日志级别