server:
  port: 9002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  devtools:
    restart:
      enabled: true  # 开启热更新
      additional-paths: src/main/kotlin
      exclude: test/**