server:
  port: 9527

# zipkin 配置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。
spring:
  cloud:
    gateway:
      routes: # 路由配置
        - id: route1
          uri: lb://cloud-payment-service
          predicates: # 配置断言
            - Path=/pay/**
            - Host={segment}.xiongkaiqi.cn:9527
          filters:
            - AddRequestParameter=foo, bar-{segment}

#        - id: route1
#          uri: lb://cloud-payment-service
#          predicates: # 配置断言
#            - Path=/pay/**
#            - My=gold,sliver #自定义predicates
#            - Query=id, \d+  # 查询参数检查
#            - Path=/pay/{id:[1-3]} # 使用SpringMvc路径匹配
#            - Host=**.xxxxxxxxxxx.cn:9527  # 指定请求访问的主机+端口（域名可用正则匹配）
#            - Header=Content-Type, application/www
#            - Cookie=token, hello_world  #有无cookie
#            - Between=2024-09-27T17:00:20.789+08:00[Asia/Shanghai],2024-09-27T17:01:20.789+08:00[Asia/Shanghai] # 在这个时间之间放行
#            - After=2024-09-27T17:00:20.789+08:00[Asia/Shanghai]  # 在这个时间之后的放行
